### ISSUE TITLE
Question: Does this utility support re-try incase Error responses from S3.

### ISSUE THREAD

**Issue by kishorekumark** [cobbzilla/s3s3mirror#100]
Hi,
I try to use this tool to copy very large s3 bucket container sub-directories and files and have different permission for objects, I'm looking weather tool can re-try if the object fails to copy due to s3 error or not.
Seeing below error while copying:
com.amazonaws.services.s3.model.AmazonS3Exception: We encountered an internal error. Please try again. (Service: Amazon S3; Status Code: 200; Error Code: InternalError; Request ID: xxxxxx, S3 Extended Request ID: yyyyyyy)

Thanks,
Kishore,

**Comment by cobbzilla** [comment]
@kishorekumark Yes, s3s3mirror performs retries just about everywhere. We understand that sometimes S3 just returns an error for no reason at all.
