### ISSUE TITLE
overwrite option

### ISSUE THREAD

**Issue by kchaitu4** [cobbzilla/s3s3mirror#104]
Hi,

Can you please add overwrite option too? Since the files names are same from source to destination, it is not copying, but the content is different and the storage class is different too.

Thanks,
Krishna

**Comment by cobbzilla** [comment]
@kchaitu4 If you want to overwrite, just "touch" the source files (update their last-modified time), so that they appear newer than the destination files. Then use the (newly added) sync strategy to only sync based on modification time.
