### ISSUE TITLE
Add the Ability to Copy Files if Size Differs or Last Modifed Datetime on the Source is After the Destination

### ISSUE THREAD

**Issue by kylec32** [cobbzilla/s3s3mirror#110]
Great tool. I have tested a ton of different tools to do this process and this has been the best one I have seen. 

Right now this tool has two different strategies for determining if an object exists in both the source and destination bucket. The default being size and etag and the other being size only. These are solid strategies but personally the strategy that the AWS CLI takes seems to be the best for my use case. The process is checking for size differences and then checking to see if the source is after the destination, in that case, do the copy. https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html 

This new proposed strategy feels like it walks the line of not missing files that were changed to be the same size as it was before while still avoiding the pitfalls of etags with differing multi-part upload chunk size. 

PR coming soon to implement this.

**Comment by cobbzilla** [comment]
@kylec32 Love it, merged the PR.

Special request -- if you can try merging this into the 2.1-stable branch that would be awesome.
