### ISSUE TITLE
Nube question - Installation on Amazon Linux

### ISSUE THREAD

**Issue by cloudlady911** [cobbzilla/s3s3mirror#42]
How do I get this to run on Amazon Linux instance.  Is there an "install" routine?  Sorry to be such a Nube

**Comment by murgurgula** [comment]
download & unzip it
Configure ur aws keys with s3cmd --configure
run the script 


For me it works with the following java:

-------------------
java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~trusty1)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)
-------------------

**Comment by cloudlady911** [comment]
I don't think I have s3cmd installed. I get this error:

[root@operator s3s3mirror-2.0-stable]# s3cmd --configure
bash: s3cmd: command not found

Same error for s3s3mirror.sh


On Mon, Apr 13, 2015 at 9:53 AM, murgurgula <notifications@github.com>
wrote:

> download & unzip it
> Configure ur aws keys with s3cmd --configure
> run the script
>
> For me it works with the following java:
> ------------------------------
>
> java version "1.7.0_75"
> OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~trusty1)
> OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cobbzilla/s3s3mirror/issues/42#issuecomment-92423670>.
>



-- 

*Laurie Kepford*
*AWS *
*Certified Solutions Architect*
Cell: 760-712-2266
email: CloudLady911@gmail.com
Skype: computerlady911
LinkedIn: www.linkedin.com/
<http://www.linkedin.com/pub/laurie-kepford/2/392/6a5/>
Website: www.LaurieKepford.com

**Comment by cloudlady911** [comment]
Nevermind, figured it out... I knew it was a fundamental thing I was forgetting.  Run with ./ so it does not search my path...

**** hangs head in shame and walks away
