### ISSUE TITLE
compiled java does not support --iam

### ISSUE THREAD

**Issue by elliotmoore** [cobbzilla/s3s3mirror#48]
FYI 
The prebuilt jar is: s3s3mirror-1.2.5-SNAPSHOT.jar which does not support --iam as documented.

thanks for your work on this project

ells

**Comment by elliotmoore** [comment]
as a helper to others, if you want a process to rebuild

This builds pretty well in https://circleci.com/ without having to modify anything
 - setup a circleci account (free tier) 
 - fork the repo and import into circleci

Under Project Settings -> Test Commands
 - Set _Test Commands_ to: (unless you want to give circle CI AWS creds for testing)
   - mvn package -Dmaven.test.skip=true 
 
 - Set _Post Test Commands_ to: (to download the artefacts)
   - cp -vp ${HOME}/s3s3mirror/target/ ${CIRCLE_ARTIFACTS}

CircleCI will build you a new s3s3mirror-1.2.5-SNAPSHOT.jar with iam support.

Please feel free to correct me if i'm mistaken

**Comment by forkonly** [comment]
I'm a CircleCI noob so excuse the ignorance ... ${HOME} env variable does not work for me.  Importing the repo should use a default path for the test VMs, correct?
See output from post test command:
```
cp: omitting directory `/home/ubuntu/s3s3mirror/target/' cp -vp ${HOME}/s3s3mirror/target/ ${CIRCLE_ARTIFACTS} returned exit code 1
```

**Comment by elliotmoore** [comment]
doh! Sorry, the cp needs `-r`, I updated above too..

**Comment by forkonly** [comment]
Nice.  I should have caught the -r myself! Thanks for the detailed instructions!  I can confirm --iam works  with the rebuilt .jar

**Comment by elliotmoore** [comment]
thanks for confirming that process works

**Comment by egeland** [comment]
This bug report is also valid for the 2.0 branch, the compiled jar seems to have no --iam option.
I may try the above CircleCI work-around, but it'd be great if the repo could be updated with a version that has this feature.

**Comment by cobbzilla** [comment]
I finally committed the updated jar for the 1.x branch, so `--iam` should now be working "out of the box" again.

The `--iam` option was never added 2.x branch. There was another pull request to merge 2.0 features into master, but it had merge conflicts. At some point I will make the switch, and we'll need to port some of the 1.x options to 2.x then.
