### ISSUE TITLE
S3ToLocalTest failing on branch 2.0-stable

### ISSUE THREAD

**Issue by DonBranson** [cobbzilla/s3s3mirror#50]
mvn clean package shows:

Results :

Tests in error: 
  testCopyFromBucketWithPrefixToDestWithOtherPrefix(org.cobbzilla.s3s3mirror.S3ToLocalTest): The bucket name parameter must be specified when uploading an object

Environment:

> java -version
> java version "1.7.0_79"
> OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0.14.04.2)
> OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
> 
> mvn -version
> Apache Maven 3.0.5
> Maven home: /usr/share/maven
> Java version: 1.7.0_75, vendor: Oracle Corporation
> Java home: /home/don/apps/jdk1.7.0_75/jre
> Default locale: en_US, platform encoding: UTF-8
> OS name: "linux", version: "3.16.0-43-generic", arch: "amd64", family: "unix"

**Comment by cobbzilla** [comment]
yup, this is a bug. I will look into it as time permits. In the meantime, I welcome a pull request if anyone is up for it.
