### ISSUE TITLE
Can't copy from bucket TO local

### ISSUE THREAD

**Issue by Jafo232** [cobbzilla/s3s3mirror#54]
Trying to do something like:

s3s3mirror.sh  s3://bucket/folder/ /some/local/path/

Doesn't appear to work.  Is there any chance of this becoming a feature?

**Comment by cobbzilla** [comment]
Have you tried the 2.0-stable branch of s3s3mirror? Your example command above should work just fine with that version.

**Comment by Jafo232** [comment]
Yes, I am using version 2.0.2

**Comment by cobbzilla** [comment]
Hmmm... that should work. Can you try this, to see if it behaves any differently:

cd /some/local/path && s3s3mirror.sh s3://bucket/folder/ ./
