### ISSUE TITLE
Unable Build the source code due to missing Jar's and other dependencies

### ISSUE THREAD

**Issue by hacholia** [cobbzilla/s3s3mirror#56]
Respected cobbzilla Team,

          I  downloaded your  s3s3mirror Project from Github for copying objects from one bucket to another.But due to some reason like log customization etc . So we want whole source code .But source code you provided on Github is not building Properly due to missing Jar's and other dependencies  So please give some solution

**Comment by cobbzilla** [comment]
Try building on Java7. There are known issues building on Java8.
