### ISSUE TITLE
Strange AWS error - missing Date /x-amz-date header / related to know aws-jdk bug?

### ISSUE THREAD

**Issue by tomthebuzz** [cobbzilla/s3s3mirror#60]
Hi Cobbzilla,
thanks for the excellent work & utility. While I had no troubles whatsoever using your utility on physical HW I seem to run into issues with a virtual environment based on OpenStack. When I execute on a HDFS name node to get some S3 files into the local FS before pushing to HDFS I get the following error from AWS:

`Thread-2 WARN : org.cobbzilla.s3s3mirror.KeyLister - getFirstBatch: error listing (try #0): com.amazonaws.services.s3.model.AmazonS3Exception: AWS authentication requires a valid Date or x-amz-date header (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 1F67DD15FB259BC8), S3 Extended Request ID: Qpbz4ietwNP+4e/7wj0MitUI5Qn6yRKU/fIYGTxeXMONdcLvRSUZRfS7+e8Ys13lQEoQ2574Hmc=
`

Might be related to a known aws-jdk-java bug discussed and resolved [here](https://github.com/aws/aws-sdk-java/issues/484) - have you ever come across this issue and know sensible way to prevent it?

Thx
-Tom

**Comment by cobbzilla** [comment]
Hi @tomthebuzz -- thanks for the kind words. I have not seen that error, but an authentication quirk in the SDK sounds plausible. One of the comments in the thread you links mentions that pinning the joda-time library to version 2.8.1 fixed the issue for them. Are you able to rebuild the s3s3mirror jar with this joda-time version and see if the error still occurs?

**Comment by appierys** [comment]
I have the same issues as well. This seems to only happen when using java8.

**Comment by tomthebuzz** [comment]
I installed an additional Java1.7 Version and everything went smoothly with that.
So thanks for a great utility.
Cheers -Tom
