### ISSUE TITLE
Some already copied files are being copied again (E-tag is not the same for multipart)

### ISSUE THREAD

**Issue by alex4598** [cobbzilla/s3s3mirror#64]
Steps to reproduce:
Bucket A - 100k+ objects
Bucket B - empty
run s3s3mirror A to B
the log reports that all files have been copied
list both buckets contents with aws s3 ls --recursive, parse key names, make diff, conclude the buckets are the same
run s3s3mirror A to B again
In my specific case, 2730 files (70GB+) ended up being copied again, even if they were the same

STATS BEGIN
read: 118642
copied: 2730
copy errors: 0
deleted: 0
delete errors: 0
duration: 0:00:57
read rate: 122925.97005646791/minute
copy rate: 2828.575869035901/minute
delete rate: 0.0/minute
bytes copied: 73.12731052096933 GB (78519851783 bytes)
GET operations: 124221
COPY operations: 2730
DELETE operations: 0
STATS END

run s3s3mirror A to B again one more time:

STATS BEGIN
read: 118642
copied: 2730
copy errors: 0
deleted: 0
delete errors: 0
duration: 0:01:09
read rate: 102581.20298584891/minute
copy rate: 2360.4346197077557/minute
delete rate: 0.0/minute
bytes copied: 73.12731052096933 GB (78519851783 bytes)
GET operations: 124221
COPY operations: 2730
DELETE operations: 0
STATS END

From the logs, I can see that the same files are being copied again and again.

Update1:
files that ended up being copied again are those having file sizes between DEFAULT_PART_SIZE and MAX_SINGLE_REQUEST_UPLOAD_FILE_SIZE
I modified those values in the code because 4GB was too heavy, and the S3 recommended chunk size is way less than that value.
So, if I use 16MB for DEFAULT_PART_SIZE and 32MB for MAX_SINGLE_REQUEST_UPLOAD_FILE_SIZE, files that have sizes between these values are copied again.

Update2:
It seems that changing back values to default does not change the outcome.

**Comment by alex4598** [comment]
It seems that E-tag is not the same for the destination object (also has a dash in it), for those particular objects:
aws s3api head-object --bucket bucket1 --key d96e5474-50cc-41a4-afba-0cc14005a513
{
    "AcceptRanges": "bytes",
    "ContentType": "application/vnd.test.article+zip",
    "LastModified": "Fri, 30 May 2014 23:17:40 GMT",
    "ContentLength": 20100083,
    "VersionId": "null",
    "ETag": "\"fdfc39b34d3596c230abee89d853028a-4\"",
    "ServerSideEncryption": "AES256",
    "CacheControl": "max-age=86400",
    "Metadata": {
        "id": "4cd0a9122412dbfc53752e4fa058e0bf0b95e8258ecd669b98b9f3e8c363481fbde3ab58162de58023fd74680b419e18fd25e337493459610e8de39b87528910da3752574f2360b34d1e8b1094266fadbc31094f6ae621f361ed4b29a80f2c5b53eba70e3a62f8b0a24cccb943291241"
    }
}
aws s3api head-object --bucket bucket2 --key d96e5474-50cc-41a4-afba-0cc14005a513
{
    "AcceptRanges": "bytes",
    "ContentType": "application/vnd.test.article+zip",
    "LastModified": "Fri, 11 Mar 2016 08:31:03 GMT",
    "ContentLength": 20100083,
    "ETag": "\"c0b2d8672a4d632df840900ca6304f7b\"",
    "ServerSideEncryption": "AES256",
    "CacheControl": "max-age=86400",
    "Metadata": {
        "id": "4cd0a9122412dbfc53752e4fa058e0bf0b95e8258ecd669b98b9f3e8c363481fbde3ab58162de58023fd74680b419e18fd25e337493459610e8de39b87528910da3752574f2360b34d1e8b1094266fadbc31094f6ae621f361ed4b29a80f2c5b53eba70e3a62f8b0a24cccb943291241"
    }
}

**Comment by alex4598** [comment]
The same applies also on reverse, when the source file has been initially uploaded with multipart and it is copied without multipart (source and destination tags does not match)

**Comment by alex4598** [comment]
Tried a fix with #65

**Comment by cobbzilla** [comment]
I'm going to close this, since I believe your other PR addresses the issue. If I'm mistake LMK and I'll re-open.
