### ISSUE TITLE
Question about long running s3s3mirror task with --ctime option

### ISSUE THREAD

**Issue by Observer99** [cobbzilla/s3s3mirror#72]
Hello,

I am going to run s3s3mirror task with --ctime option, let's say --ctime 20d that will be running for a week or so due to huge amount of data that should be copied.
The option --ctime 20d means that s3s3mirror should copy only objects whose Last-Modified date is younger than 20 days. I want to copy objects since May 1. My concern is how s3s3mirror calculate it for current object? If I run the job on May 20, s3s3mirror should copy all objects since May 1, but after one day of execution, let's say on May 21, will s3s3mirror continue to take objects since May 1? Or s3s3mirror calculates it every time  for current object and will only copy objects since May 2?

**Comment by cobbzilla** [comment]
The ctime used for comparisons is calculated just once, at startup time, so s3s3mirror will run for a finite amount of time.
