### ISSUE TITLE
Keep getting exceptions trying to move from one bucket to another. 

### ISSUE THREAD

**Issue by bytor99999** [cobbzilla/s3s3mirror#73]
I keep getting the following exceptions. 

Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method.

I have set env variables for our access key and secret access key that work with aws-cli. But not sure what else could be needed.

./s3s3mirror.sh https:/bucket1NameHere.s3.amazonaws.com/folderName https://bucket2NameHere.s3.amazonaws.com/folderName

Thanks

Mark

**Comment by bytor99999** [comment]
Just an FYI, I am using the S3 Console in AWS for now. But it still would be interesting and nice to use your great project in the future for these needs.

Thanks

Mark

**Comment by cobbzilla** [comment]
@bytor99999 the syntax for your command should be something like this

    ./s3s3mirror.sh bucket1NameHere/folderName bucket2NameHere/folderName

Could you try that and tell me if the same error occurs?

**Comment by bytor99999** [comment]
Thanks Cobb. I will try that this next week when I get back into work.

**Comment by cobbzilla** [comment]
@bytor99999 any luck with it?

**Comment by Sakibs** [comment]
I get the same error as well.
The aws cli on my machine works fine and all the commands work on it. But when using this utility, for each file it shows me the error above. I tried to add the access key and secret key in ~/.s3cfg and I ran the aws configure command with no luck

**Comment by bytor99999** [comment]
I apologize that I have not had a chance to get back to this. Haven't had a reason to move one bucket to another in a long long while.

**Comment by joekohlsdorf** [comment]
I got this error for files which had UTF-8 in their metadata using `openjdk version "1.8.0_181"`.
