### ISSUE TITLE
Option for handling missing metadata

### ISSUE THREAD

**Issue by gpip** [cobbzilla/s3s3mirror#76]
Hello,

I have a bucket where some objects were "miscopied" and their metadata are empty while they should have something. Now, when running s3s3 mirror I'm receiving

`org.cobbzilla.s3s3mirror.KeyCopyJob - Error getting metadata for <bucket name>/<key> (not copying): java.lang.NullPointerException`

for those files. Is there some way to overwrite the destination file and let s3s3mirror write the correct metadata instead of ignoring them?

**Comment by cobbzilla** [comment]
This is a great suggestion, and s3s3mirror should definitely support this. I'm marking this issue "bug", and hope to get to it soon. If someone beats me to it, I will welcome the pull request.

**Comment by thewoolleyman** [comment]
Has there been any progress on this?

If not, are there any workarounds?

If we do consider making a PR, any idea on how difficult the bug fix would be, or pointers to the code that would need to be changed?

Thanks...
