### ISSUE TITLE
Problems authenticating

### ISSUE THREAD

**Issue by stadskle** [cobbzilla/s3s3mirror#77]
Hi,

Sorry, this is likely an issue on my side, but I cannot see the issue. I have set system variables (OSX) using this on the command line

export AWS_ACCESS_KEY_ID=xxxx
export AWS_SECRET_ACCESS_KEY=xxxx

I verify the values using 
echo $AWS_SECRET_ACCESS_KEY
echo $AWS_ACCESS_KEY_ID

and I can see the values being printed. However, when I run 

sudo sh s3s3mirror.sh bucket1 bucket2 I get

Could not find credentials, IAM Role usage not specified and ENV vars not defined: AWS_ACCESS_KEY_ID and/or AWS_SECRET_ACCESS_KEY

I have also added a file in my home dir .s3cfg
access_key=xxxx
secret_key=xxxx

But that makes no difference either. Anything missing from the documentation or is it I who is doing something wrong?

**Comment by cobbzilla** [comment]
You can use `sudo -E` to preserve the environment. If you want to use the `~/.s3cfg` approach, run this command to determine where your subshell considers "HOME": `sudo sh echo "${HOME}"`, then make sure there is a `.s3cfg` file in that home directory.
