### ISSUE TITLE
Error copying into local directory

### ISSUE THREAD

**Issue by hierony94** [cobbzilla/s3s3mirror#78]
I'm try using 2.0-stable and 2.1-stable branch to copy files from S3 bucket to my local directory.
I'm running it using this command `./s3s3mirror.sh my_bucket local_directory`

It successfully copy several files, but also error when copying several file.
This is the error log :

```
pool-1-thread-56 WARN : org.cobbzilla.s3s3mirror.store.local.LocalFileStore - Error creating parent directory: /home/ubuntu/OFS/temp/typo3temp/cs
pool-1-thread-56 ERROR: org.cobbzilla.s3s3mirror.store.s3.job.S3CopyToLocalJob - unexpected exception copying (try #4) temp/typo3temp/cs/csascii_utf-8.tbl to: temp/typo3temp/cs/csascii_utf-8.tbl: java.io.FileNotFoundException: /home/ubuntu/OFS/temp/typo3temp/cs/csascii_utf-8.tbl (Not a directory)
pool-1-thread-63 WARN : org.cobbzilla.s3s3mirror.store.local.LocalFileStore - Error creating parent directory: /home/ubuntu/OFS/trashdir/f7/87
pool-1-thread-63 ERROR: org.cobbzilla.s3s3mirror.store.s3.job.S3CopyToLocalJob - unexpected exception copying (try #4) trashdir/f7/87/f787af1fc8c2c9f6f933e15584b7c5dbfa041b41 to: trashdir/f7/87/f787af1fc8c2c9f6f933e15584b7c5dbfa041b41: java.io.FileNotFoundException: /home/ubuntu/OFS/trashdir/f7/87/f787af1fc8c2c9f6f933e15584b7c5dbfa041b41 (Not a directory)
pool-1-thread-25 ERROR: org.cobbzilla.s3s3mirror.store.s3.job.S3CopyToLocalJob - unexpected exception copying (try #4) lock/f2/f2443adc3bc0173e699482de29482635 to: lock/f2/f2443adc3bc0173e699482de29482635: java.io.FileNotFoundException: /home/ubuntu/OFS/lock/f2/f2443adc3bc0173e699482de29482635 (Not a directory)
```

And also i'm found that in branch 2.x, there're no support to read the credential from ~/.s3cfg.
CMIIW if I'm wrong

Please help me what is wrong in my step.
Thank You.

**Comment by cobbzilla** [comment]
My best guess is that when copying from S3 to local, there is a bug in that we do not appropriately create parent directories. If you are able to, can you create the directories that s3s3mirror complains are missing, and re-run the command? If my thinking is correct, it should work now that all the appropriate parent directories exist in your local directory. If this is the case, it's definitely a bug, but at least there is a somewhat decent workaround.

**Comment by hierony94** [comment]
Hello @cobbzilla,

There're too many parent directory to be created manually.
I can't create all of the parent directory.

Is any another way that I can do to achieve it?

**Comment by hierony94** [comment]
Update @cobbzilla 
Thanks for this https://arstechnica.com/civis/viewtopic.php?f=19&t=303577, Now I can copy directory structure of source bucket with this command `find source_dir -type d -exec mkdir dest_dir/\{\} \;`

After I copied the directory structure, I run this command again `./s3s3mirror.sh my_bucket local_directory`. The problem still exist (some files copied, some doesn't copied), but now I'm got a new error, the error is :
```

**Comment by cobbzilla** [comment]
try adding a trailing slash (`/`) to one or both paths.
