### ISSUE TITLE
S3 copy not working with prefix 

### ISSUE THREAD

**Issue by joelnishanthreddy** [cobbzilla/s3s3mirror#80]
When i am trying to copy objects from BucketA/test/\* to BucketB/  it is copying the "test" directory as well. 

Example : 
./s3s3mirror.sh -P Profile -p test BucketA BucketB 

OR 

./s3s3mirror.sh -P Profile BucketA/test/file1 BucketB/ 

OutPut: 

Actual Output : BucketB/test/file1 

Desired Output : BucketB/file1

**Comment by cobbzilla** [comment]
could you try using a prefix of `test/` and let me know if it still occurs?

**Comment by joelnishanthreddy** [comment]
Still occurs when i use test/* it creates a test/ directory which is not how its supposed to behave.

**Comment by cobbzilla** [comment]
I set up some test buckets and ran some commands, I was able to perform a copy like the one you want, it looks like this:

`s3s3mirror.sh source-bucket/test/ dest-bucket`

Give that a whirl and let me know how it goes.
