### ISSUE TITLE
s3s3mirror.KeyLister - No more keys found in source bucket, exiting

### ISSUE THREAD

**Issue by andrewm-bridgit** [cobbzilla/s3s3mirror#82]
I made a successful initial mirror of an S3 bucket, but subsequent running of the script (./s3s3mirror s3://<source_bucket> s3://<destination_bucket) to keep the mirrored bucket up-to-date fails with the error

pool-1-thread-1 INFO  s3s3mirror.KeyLister - No more keys found in source bucket, exiting
pool-1-thread-26 INFO  http.AmazonHttpClient - Unable to execute HTTP request: Connection reset
java.net.SocketException: Connection reset

**Comment by cobbzilla** [comment]
That message indicates that the listing of the source bucket has completed. If it happens without copying anything, it usually means there was nothing to actually copy. Can you confirm that there are some objects in the source bucket when you get this message?
