### ISSUE TITLE
non fatal log4j error

### ISSUE THREAD

**Issue by erunaheru** [cobbzilla/s3s3mirror#83]
Not sure if it's because of calling from cron or because I'm running in docker, but I was getting "`log4j:ERROR Could not parse url [file:target/conf/log4j.xml]`" and an equivalent java IO error. Fixed it by changing the main line of the start script to "`java ${VERSION_ARG} -Dlog4j.configuration=file:${THISDIR}/target/conf/log4j.xml -jar "${JARFILE}" "$@"`"

**Comment by cobbzilla** [comment]
thanks if you have a PR that fixes this I would be happy to review/add

**Comment by cobbzilla** [comment]
closing, this has been fixed.
