### ISSUE TITLE
No open source license

### ISSUE THREAD

**Issue by pkrish** [cobbzilla/s3s3mirror#85]
Adding a license will help others use the project in an appropriate way. 

You can use this site made by github.com to choose a license. 
https://choosealicense.com/

**Comment by cobbzilla** [comment]
did you see https://github.com/cobbzilla/s3s3mirror/blob/master/pom.xml#L5 ?

**Comment by pkrish** [comment]
Thanks, that works. 

I missed it since I was looking for a license file. 
http://stackoverflow.com/questions/31639059/how-to-add-license-to-an-existing-github-project

**Comment by cobbzilla** [comment]
It's OK. I just added a license file too, so it should be more clear.
