### ISSUE TITLE
Issue with cross-account-copy 

### ISSUE THREAD

**Issue by xmikelopez** [cobbzilla/s3s3mirror#91]
Hi, 

We are seeing the following error when using --cross-account-copy using a profile key that has cross account access:

pool-1-thread-56 WARN : com.amazonaws.services.s3.AmazonS3Client - Region information for null is not available. Please upgrade to latest version of AWS Java SDK

Anyway, Thank you for providing this awesome tool!

Cheers,
Mike

**Comment by cobbzilla** [comment]
@xmikelopez  closing this as the AWS SDK was recently updated to the latest version.
