### ISSUE TITLE
Use AWS SDK CredentialProviders instead of manually parsing config files

### ISSUE THREAD

**Issue by gschneider-r7** [cobbzilla/s3s3mirror#93]
The AWS SDK has different CredentialProvider implementations that would be better to use here than most of the current methods for getting credentials. For example, when I pass in a profile parameter the [ProfileCredentialsProvider](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/index.html?com/amazonaws/auth/profile/ProfileCredentialsProvider.html) should be used, which will handle finding the credentials in the appropriate file (in my case, it's `~/.aws/credentials`) and refreshing the session if necessary.

**Comment by cobbzilla** [comment]
merged, closing
