### ISSUE TITLE
Error getting metadata for (not deleting)

### ISSUE THREAD

**Issue by webslice** [cobbzilla/s3s3mirror#99]
Hello,

I run version 1.2.6 of s3s3mirror.

When I execute the following;

./s3s3mirror.sh --dry-run -X (bucket source) (bucket destination) 

After a while I receive a WARN:

pool-1-thread-21 WARN : org.cobbzilla.s3s3mirror.KeyDeleteJob - Error getting metadata for (source bucket)/uploads/517/watermark_1a30480915867ccd7741189096a65f56203bbf4a.jpg (not deleting): com.amazonaws.SdkClientException: Unable to execute HTTP request: (source bucket).s3-eu-west-1.amazonaws.com

Which results in a lot of these 'Error getting metadata for' / 'Unable to execute HTTP request' warnings. 

Do you have any idea what could cause this? Thank you in advance.

Kind regards,
Oscar.

**Comment by GBR-422777** [comment]
Is this issue being tackled?

**Comment by cobbzilla** [comment]
@GBR-422777  I am unable to duplicate this behavior. My best guess is that you are being rate-limited, and that is generating HTTP errors.
